### ISSUE TITLE
Не переключается значение фильтров с числовыми значениями при переключении валюты

### ISSUE THREAD

**Issue by kamuz** [andchir/shopkeeper3#11]
Возможность перелючения валюты предусмотрена.

> 1. Если используется аякс-фильтрация, открыть в текстовом редакторе */assets/components/tag_manager2/js/web/filters.js* и включить мультивалютность - `multi_currency: true`.
> 2. В этом же файле указать правильное название TV параметра или поля с ценой - `price_field`.
> 3. В настройках системы в параметре `tag_mgr2.priceName` нужно указать название TV параметра или поля с ценой (по умолчанию `price`).
> 4. Версия Shopkeeper должна быть не меньше 2.3.4.

По третьему пункту - такой настройки не было и я её создал вручную с указанным параметром.

Все остальное также соблюдено.

Но ничего не происходит после этого. Тоесть валюта перелючается на всём сайте, но не обновляются значения фильтров, тоесть используя фильтрацию по цене, в URL подставляются не верные значения.

![ULR](http://joxi.net/DrlpjQZFvb7DBr.jpg)

**Сайт находится на [тестовом домене](http://918695.doskadpk.web.hosting-test.net/), могу дать доступы.**

**Comment by kamuz** [comment]
Нашёл место где это может менятся https://github.com/andchir/shopkeeper3/blob/master/core/components/tag_manager2/model/tm_catalog.class.php#L145

**Comment by kamuz** [comment]
Но а что делать пока не разобрался

**Comment by kamuz** [comment]
В лог записывается следующая ошибка 

```
[2016-12-09 13:47:34] (ERROR @ D:\xampp\htdocs\shkstart.loc\core\components\tag_manager2\model\tm_base.class.php : 49) PHP warning: explode() expects parameter 2 to be string, array given
```

https://github.com/andchir/shopkeeper3/blob/master/core/components/tag_manager2/model/tm_base.class.php#L49

Хотя мультизначения у меня работают вроде как нормально. Возможно это старые логи - уже ничего не записывается

**Comment by kamuz** [comment]
https://github.com/andchir/shopkeeper3/blob/master/core/components/tag_manager2/model/tm_base.class.php#L49

**Comment by kamuz** [comment]
Хотя мультизначения у меня работают вроде как нормально

**Comment by kamuz** [comment]
Возможно это старые логи - уже ничего не записывается

**Comment by andchir** [comment]
Я уже не помню, почему, видимо ТагМанагер 2.0 появился раньше чем Шопкипер 3.0. В настройках системы должны быть параметры:

**shk.currency_rate** - Курсы валют. Пример значения: ``руб.==1||грн==3.1||USD==34||euro==46``
**shk.currency_default** - Номер валюты по умолчанию

В текущей версии мультивалютность не адаптирована под SHK 3.

**Comment by kamuz** [comment]
Спасибо, помогло. Правда в моём случае нужно было поставить другой порядок и значения валют. Закрыть задачу или пускай висит, чтобы поправить это в следующей версии для указания курса валют в одном месте?

**Comment by andchir** [comment]
Задача пусть висит.
