### ISSUE TITLE
Сделать совместимость с jQuery 3.0

### ISSUE THREAD

**Issue by andchir** [andchir/shopkeeper3#14]

**Comment by shamarin** [comment]
Спасибо, что включили в список. Сегодня хотел создать тикет. На данный момент есть не совместимость. Ругается на файл shopkeeper.js на строку 19 с ошибкой "TypeError: $(...).size is not a function". И на код вызываемый в head страницы "TypeError: SHK is undefined":
```
<script type="text/javascript">
        SHK.data = {"price_total":"0.00","items_total":0,"items_unique_total":0,"delivery_price":0,"delivery_name":"","ids":[]};
        jQuery(document).bind( 'ready', function(){
            SHK.init( {"prodCont":"div.shk-item","site_base_url":"\/","counterField":false,"counterFieldCart":true,"changePrice":"1","flyToCart":"helper","noLoader":false,"allowFloatCount":false,"animCart":true,"goToOrderFormPage":false,"orderFormPageUrl":"\/shopping-cart\/","debug":true} );
        });
	</script>
```

**Comment by andchir** [comment]
Пока вы можете сами сделать совместимость. Для этого надо
все ``.size()`` заменить на ``.length``
и все `` jQuery(document).bind( 'ready',`` на `` jQuery(document).ready(``

**Comment by shamarin** [comment]
После правки все замечательно работает. Еще у вас в коде есть запрещенный элемент `.bind ()` его нужно заменять на `.on ()`
