### ISSUE TITLE
Кнопка "Подгрузить еще"

### ISSUE THREAD

**Issue by fatijio** [andchir/shopkeeper3#2]
Большая просьба реализовать в следующих версиях SHK подгрузку товаров в категории кнопкой Подгрузить еще...

**Comment by andchir** [comment]
Пока обновленный демо-сайт не релизнулся, решение:
1. Закачать себе на сервер этот скрипт: https://github.com/andchir/shopkeeper3/blob/master/assets/components/tag_manager2/js/web/one_page_pagination.js
2. Обновить этот скрипт: https://github.com/andchir/shopkeeper3/blob/master/assets/components/tag_manager2/js/web/view_switch.js
3. Обновить файл: https://github.com/andchir/shopkeeper3/blob/master/core/components/tag_manager2/ajax_resources.php
4. Подключить скрипт так: https://github.com/andchir/shopkeeper3/blob/master/assets/template/catalog_category2.html#L90-L98
Кнопка "Показать ещё" такая:
https://github.com/andchir/shopkeeper3/blob/master/assets/template/catalog_category2.html#L77-L83

**Comment by fatijio** [comment]
круто, спасибо, в следующей сборке это уже будет вшито ?

**Comment by godlatro** [comment]
Добавил себе, на предыдущую версию шопа, все работает как надо. Хотя не обновляет цифры при смене количества выводимых на странице товаров. Наверное потому что оно работает через аякс + гет. Решил пока просто избавиться от цифр в кнопке

**Comment by godlatro** [comment]
Обнаружилась проблема все-таки, постраничная навигация теперь тоже работает подгрузкой, а не как надо

**Comment by andchir** [comment]
> Обнаружилась проблема все-таки, постраничная навигация теперь тоже работает подгрузкой, а не как надо

Там где нужна обычная постраничная навигация - не должно быть скрипта "one_page_pagination.js".

> Хотя не обновляет цифры при смене количества выводимых на странице товаров

У меня обновляет. Может не все файлы вы у себя обновили или что-то не правильно сделали.

**Comment by godlatro** [comment]
А есть возможность совместить оба варианта? К сожалению модх плагины не часто обновляются.
