### ISSUE TITLE
Отобразить описание параметров для сниппета Shopkeeper

### ISSUE THREAD

**Issue by kamuz** [andchir/shopkeeper3#3]
Очень было удобно было в Shopkeeper 2, когда при клике отображалось описание того что именно означает тот или иной параметр, при этом не нужно было лесть в документацию.

[screenshot](http://new.promo-creative.com/assets/temp/11-14-2016%2012-58-11.png)

**Comment by andchir** [comment]
Это уже сделано в новой версии, которую можно скачать здесь http://forum.modx-shopkeeper.ru/topic/456/%D0%B2%D1%8B%D1%88%D0%B5%D0%BB-shopkeeper-2-3-5rc1

**Comment by kamuz** [comment]
Отлично - можно и сюда загрузить релиз, а то пока что [нет ничего](https://github.com/andchir/shopkeeper3/releases)
