### ISSUE TITLE
Сделать документацию в Markdown

### ISSUE THREAD

**Issue by kamuz** [andchir/shopkeeper3#4]
Можно поместить в README.md чтобы удобно было сразу же читать документацию с репозитория, как это сделанно в остальных проектах. Я уже это сделал и могу поделится. На своём сайте я также публикую подобную информацию и выглядит это [так](http://new.promo-creative.com/shopkeeper.html).

**Comment by andchir** [comment]
Для этого есть вики документация http://wiki.modx-shopkeeper.ru/
Там есть возможность публиковать в Markdown.
