### ISSUE TITLE
Не клонируется папка core

### ISSUE THREAD

**Issue by kamuz** [andchir/shopkeeper3#5]
Если качать архивом загружается наверно вся информация, даже *config.core.php* и *index.php* CMS MODX.

Но если через Git

```bash
git clone git@github.com:andchir/shopkeeper3.git
```

То папка *core/*, *dump.sql* и т. д. не загружаются. Проверил *.gitignore* там вроде это не прописанно.

**Comment by andchir** [comment]
``git clone https://github.com/andchir/shopkeeper3 ``
Так клонируется нормально.
