### ISSUE TITLE
Добавить возможность отключать JS функционал в наборах параметров

### ISSUE THREAD

**Issue by kamuz** [andchir/shopkeeper3#7]
Для некоторых проектов лучше не использовать лоадер, который появляется после добавления или удаления товара, а также подтвержающее окошко удаления товаров. Как правило они просто появляются либо не в том месте где нужно или же двух местах одновременно, в том случае если используется 2 корзины на странице.

Естественно эти вещи можно было поправить в CSS или залесть в код *shopkeeper.js* чтобы решить эту задачу, но гораздо проще было отключить их в наборах параметров сниппета Shopkeeper

**Comment by andchir** [comment]
Есть параметр "noLoader".

**Comment by kamuz** [comment]
Не заметил. В readme.txt об этом не сказанно. Нужно дописать. Обратил внимание что в документации, которая идёт вместе с пакетом содержится всего 22 параметра, а по факту 35. Желательно всех их дописать что каждый делает и тогда я думаю подобных вопросов будет поменьше.

**Comment by kamuz** [comment]
Раньше было понятней, когда к каждому параметру шло описание в наборах параметров или на странице со сниппетом. Но раз ты говоришь, что в следующей версии это добавленно - тогда гуд.
