### ISSUE TITLE
Как собрать пакет вручную?

### ISSUE THREAD

**Issue by kamuz** [andchir/shopkeeper3#8]
Я работаю под Windows и во первых не все файлы клонируются с GitHub, а во вторых появляются ошибки. Я также пробовал собрать 2-й Shopkeeper, но у меня это не получилось. Для того чтобы собрать я просто запускал [файл этот файл](https://github.com/andchir/shopkeeper3/blob/master/_build/shopkeeper3/build.transport.php) через адресную строку браузера, при этом код Shopkeeper находился в корне сайта.

**Comment by andchir** [comment]
Если не все файлы клонируются, значит в этом и причина. Надо научиться клонировать.
