### ISSUE TITLE
Исправить некорректную работу в админке нескольких tv с типом ввода param-edit

### ISSUE THREAD

**Issue by pooding55** [andchir/shopkeeper3#9]
Если в проекте есть несколько TV с типом ввода param-edit, то в админке происходит следующее: после редактирования одного из TV, при попытке редактировать следующее - поле ввода переносится туда, где располагается первое отредактированное TV.
Вот пример. Сначала отредактировал "Третье блюда" - всё прошло хорошо. Потом пытаюсь редактировать "Салат" и получаю такой перенос формы ввода. 
http://s017.radikal.ru/i421/1612/34/31ca279a3511.png

**Comment by tsergey88** [comment]
Добавлю на тему ошибки с типом ввода param-edit.
При использовании нескольких TV с параметром ввода param-edit, настроить можно только один, все последующие будут иметь настройки самого первого, не зависимо от того что указано в настройках других TV

**Comment by andchir** [comment]
Ещё сообщение об этой проблеме:
http://forum.modx-shopkeeper.ru/topic/711/tv-%D1%81-%D1%82%D0%B8%D0%BF%D0%BE%D0%BC-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0-param_edit-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-%D0%B2-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%BA%D0%B5

**Comment by andchir** [comment]
Исправлено здесь: https://github.com/andchir/shopkeeper3/blob/master/core/components/shopkeeper3/elements/tv/tpl/input_param-edit.tpl
